# Generated by Django 4.0.6 on 2022-07-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone number')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
            ],
        ),
    ]
